server:
  port: 9090

zuul:
  ignored-services: '*'
  routes:
    api-1:
      path: /app/**
#
#hystrix:
#  command:
#    myusers-service:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds:  ...

api-1:
  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    ## 服务节点
    listOfServers: localhost:1001,localhost:1002,localhost:1003
    ## 分发策略
#    NFLoadBalancerRuleClassName: com.zxl.test.boszuul.rules.IpUserHashRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    ## 健康检查
    NFLoadBalancerPingClassName: com.zxl.test.boszuul.configs.HealthExamination
    NFLoadBalancerPingInterval: 20
    ConnectTimeout: 60000
#    ReadTimeout: 3000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100

ribbon:
  eureka:
    enabled: false